<?php
//IMPORTANTE: CONSTANTES E ARRAY CONSTANTES
//DEFINIR UMA CONSTANTE - NOME E VALOR
//SEMPRE MAIUSCULAS
//NAO COMECAM COM $
define("SERVIDOR","127.0.0.1");
echo SERVIDOR;
echo "<br/>";
//CONSTANTES GLOBAIS
#versao do php
echo PHP_VERSION;
echo "<br/>";
#tipo de barra que separa os diretorios nos diferentes SO utilizados
echo DIRECTORY_SEPARATOR;
echo "<br/>";
//CONSTANTE COMPOSTA POR UM ARRAY - NOVIDADE NO PHP7
//EXEMPLO DE UMA CONSTANTE COM OS DADOS PARA ACESSO AO BD
//O TRUE NO FINAL DA DECLARACAO DA VARIAVEL INDICA QUE ELA NAO É KEYSENSETIVE
//POR CONVENCAO NAO SE USA POIS A BOA PRATICA RECOMENDA O USO DE CONSTATANTES TODAS EM MAIUSCULO!!!
define("BANCO_DE_DADOS",[
    '127,0,0,1',
    'root',
    'password',
    'bdname'
],true);
?>
<pre>
<?php
print_r(BANCO_DE_DADOS);
?>
</pre>