<?php
//EXEMPLO DE AUTOLOAD
//A ARQUIVO TEM QUE TER O MESMO NOME DA CLASSE QUE VAI INVOCAR
//ESSE CODIGO VAI FUNCIONAR JUNTO COM O AUTOMOVEL.PHP
//ESSES CODIGOS FORAM DESMEMBRADOS DO ARQUIVO CLASSEABSTRATA.PHP
//classe extended para usar a classe ABSTRACT AUTOMOVEL
class DelRey extends Automovel {
    public function empurrar(){

    }
}