<?php
//CONEXAO COM UM BANCO DE DADOS ATRAVES DA CLASSE MYSQLI, POR SER NATIVA DO PHP ESSA CLASSE É TODA EM MINUSCULA
//CRIA UM OBJETO COM ESSA CLASS, PASSANDO OS PARAMETROS (SERVIDOR, USUARIO, SENHA, BANCODESEJADO)
$conn = new mysqli("localhost","user","senha","dbphp7");
//TRATAR ERRO DE CONEXAO
if($conn->connect_error) {
    echo "Error: ".$conn->connect_error;
}
//APOS CONECTAR VAMOS TRABALHAR
//FAZER UM INSERT NA BASE DBPHP7 PREPARE("COMNADO SQL")
//IMPORTANTE:
//OS VALORES DO CAMPO VALUE OU DOS CAMPOS QUE ENVIAREM VALORES, SAO PREENCHIDOS COM ? - AS PROXIMAS ACOES DEFINIRAO OS "TIPOS" E OS "VALORES" DESSE CAMPO.
$stmt = $conn->prepare("INSERT INTO tb_usuarios (deslogin, dessenha) VALUES(?, ?)");
//AGORA PRECISAMOS PREPARAR OS TIPOS DE VALORES DO VALUE
//O BIND_PARAM RECEBE ENTRE ASPAS OS TIPOS DA VARIAVEIS ENVIADAS E OS VALORES
//s - string, i - inteiro, f - float, b - bloob
//COMO SAO DUAS STRINGS => ss, string1, string2 
//IMPORTANTE:
//O BIND_PARAM RECEBE VARIAVEIS POR REFERENCIA, TEM UM &$VARIAVEL NO ARGUMENTO DO METODO, ENTAO É OBRIGATORIO PASSAR VARIAVEIS NOS ARGUMENTOS DA CHAMADA DO METODO.
//--------- NAO DA PARA COLOCAR DIRETAMENTE OS VALORES NOS PARAMETROS DO METODO!!!
$stmt->bind_param("ss", $login, $pass);
//DECLARAR AS VARIAVEIS ANTES OU DEPOIS DA CHAMADA É INDIFERENTE, POIS AINDA ESTAMOS PREPARANDO O "COMANDO SQL" QUE SERA EXECUTADO. É NECESSARIO CLARO ESTAR TUDO OK ANTES DE CHAMAR O METODO EXECUTE - ELE MANDA O "PACOTE" PREPARADO PARA O BANCO!!!! 
$login = "user"; 
$pass =  "123456";
//EXECUTA O COMANDO PREPARADO E PARAMETRIZADO
$stmt->execute();
//IMPORTANTE:
//O MAIS BACANA DESSE PROCESSO É QUE UMA VEZ PREPARADO O STATEMENTE (A LINHA SQL) DO BD, SÓ É NECESSARIO ALTERAR AS VARIAVEIS E CHAMAR O METODO EXECUTE(). A CADA EXECUTE ELE ENVIA OS VALORES GRAVADOS NAS VARIAVEIS - NESTE CASO - $LOGIN E $PASS
$login = "Joao Roberto";
$pass = "4323@#5";
$stmt->execute();
$login = "Maria Goes";
$pass = "feraew$#%6f";
$stmt->execute();
$login = "Pedro Boom";
$pass = "FE3435ed#ft$#";
$stmt->execute();
//A CADA EXECUTE É ENVIADO O PACOTE PARA O BANCO E É INCLUIDO OS VALORES FIXADOS NAS VARIAVEIS